### PR TITLE
fix(Ui-Toolkit) - Add syntax highlighting

### LINKED ISSUE #740: Update styleguide code theme
https://react-styleguidist.js.org/docs/configuration.html#highlighttheme

Themes: http://codemirror.net/demo/theme.html

- border #d8d8d8
- background #fafafa
- spacing (eg padding) to use multiples of 3px
- default text colour #494949
- line numbers text colour #636363

### PR DESCRIPTION
**Pull request by SaraVieira**
closes #740 

https://styleguide-zpemazdqgu.now.sh/

Also perfects ui in radio button validation

### CODE REVIEW

File: packages/ui-toolkit/src/styleguide/wrapper.js [hunk 1]
```diff
@@ -3,6 +3,7 @@ import { ThemeProvider, injectGlobal } from 'styled-components';
 import theme from '../theme';
 import Base from '../base';
 import { loadedFontFamily } from '../typography';
+import 'react-codemirror2/node_modules/codemirror/mode/jsx/jsx';
```
Comment (SaraVieira) [inline packages/ui-toolkit/src/styleguide/wrapper.js]: Styleguidist bug :(
