### PR TITLE
fix list-item

### LINKED ISSUE #281: fix list item style [#208]
#208

### PR DESCRIPTION
**Pull request by ramitos**

### CODE REVIEW

File: ui/src/components/list/group-view.js [hunk 1]
```diff
@@ -1,15 +1,17 @@
...
 import { colors } from '../../shared/constants';
 import { remcalc } from '../../shared/functions';
-import { raw as View } from './view';
+import View from './view';
 import styled from 'styled-components';
 
 const GroupView = styled(View)`
   display: block;
+
   padding-top: ${remcalc(62)};
```
Comment (alex-windett) [inline ui/src/components/list/group-view.js]: Could be written shorthand :
`padding: ${remcalc(62, 23, 5, 23)}`
Me just being picky

Comment (ramitos) [inline ui/src/components/list/group-view.js]: ofc, good call d'oh 😉
